### ISSUE TITLE
Could not resolve "@codemirror/fold"

### ISSUE THREAD

**Issue by voraciousdev** [replit/codemirror-vim#10]
The `@codemirror/fold` dependency is not listed as a peer dependency but is required to use this extension.

```
node_modules/@replit/codemirror-vim/dist/index.js:7:25:
  7 │ import { foldCode } from '@codemirror/fold';
```

**Comment by sergeichestakov** [comment]
Good catch, thanks! Fixed in https://github.com/replit/codemirror-vim/commit/988669a192473d5464aa9e78513f5c6ef8f32f2d
