### ISSUE TITLE
Bugs with marking a block in visual mode when the cursor is not within the block

### ISSUE THREAD

**Issue by ethanppl** [replit/codemirror-vim#101]
Say, there is a line

```js
import { basicSetup, EditorView } from 'codemirror'
```

Placing the cursor at any place outside the `{ ... }` block and do `va{`

- Expected: jump to the closest block and highlight `{ basicSetup, EditorView }`
- Reality: it failed to jump to the bracket, but just highlighted the current and the previous letter
- The same happens for `vi{`, `viB`, `vaB`, and `vi` plus other characters like `'`, `"`, `(`, `[`

Thanks!

**Comment by ethanppl** [comment]
The ability to switch between inner and outer bracket pairs is not important to me. I don't have a preference for this. I guess this depends on what version of vim does this repository trying to mirror. Thanks for the work :)

**Comment by nightwing** [comment]
I guess we should try to match the latest version, please check if https://raw.githack.com/replit/codemirror-vim/block-text-object/dev/web-demo.html works the way you are expecting.

**Comment by ethanppl** [comment]
> I guess we should try to match the latest version, please check if https://raw.githack.com/replit/codemirror-vim/block-text-object/dev/web-demo.html works the way you are expecting.

Seems great, thanks a lot!
