### ISSUE TITLE
The `:norm` command does not seem to be working

### ISSUE THREAD

**Issue by ElijaRock** [replit/codemirror-vim#103]
I am not sure if the `:norm` command is meant to be implemented into this repo, but if it is it's not functional. `:normal` does not work either and gives the response that it is not an editor command on the demo website. This makes it difficult to edit multiple lines at once using normal commands in obsidian (the markdown editing software I am using with codemirror vim bindings).

**Comment by nightwing** [comment]
Could you check if changes from https://github.com/replit/codemirror-vim/pull/105 (which can be tested on https://raw.githack.com/replit/codemirror-vim/2e78f6f/dev/web-demo.html) work as you expect them to.
