### ISSUE TITLE
<s-p> Shift-P command paste multiline content but not _forward_

### ISSUE THREAD

**Issue by stealzy** [replit/codemirror-vim#106]
Tested in chrome qwerty: https://codemirror-vim--util.repl.co/
```
█irst
second
third
```
Running `v3jyP`. Expected:
```
█irst
second
third
first
second
third
```
Got:
```
first
second
third
█irst
second
third
```
It happens when register content is multiline, but not *line-wise*. There is no way to avoid this bug if you need to paste from system clipboard.

**Comment by nightwing** [comment]
Could you explain in more detail what do you mean. Running `dwP` in codemirror works the same way as in vim itself.

**Comment by stealzy** [comment]
Test here: https://codemirror-vim--util.repl.co/
`P` works like `p` for me. Running `yeP` for example.

**Comment by stealzy** [comment]
I got cursor at first symbol first line:
```
first line
second
third
```
Running `y3d`, `P`.
I expect cursor stay on same position, and buffer inserted after cursor.
Instead cursor moved to end of insertion (like `p` behave).

**Comment by nightwing** [comment]
With which operating system, browser, and keyboard layout do you see this? This still works correctly for me on windows, chrome, qwerty layout.

**Comment by stealzy** [comment]
```
█irst
second
third
```
Running `v3jyP`.
Windows, chrome, qwerty layout.

**Comment by nightwing** [comment]
As far as i can tell it is not a difference between p and P, but multiline and single line pasted text. 
https://raw.githack.com/replit/codemirror-vim/fix-cursor-after-p/dev/web-demo.html seems to behave the same way as vim, please check.
