### ISSUE TITLE
Toggling insert mode doesn't work after highlighting text in visual mode

### ISSUE THREAD

**Issue by sergeichestakov** [replit/codemirror-vim#108]
See title. Repro is as follows:
1. Enter visual mode
2. Highlight some text (e.g. by moving cursor several lines down)
3. Hit "i"
4. Notice that you're not in insert mode when you should be

See demo (not visible is me hitting "i" numerous times after highlighting):

![cm-vim-highlight-insert](https://user-images.githubusercontent.com/24947334/232921534-9ca1fa14-89ce-4fb3-8428-889dacea982e.gif)

**Comment by nightwing** [comment]
Running `vi` does not enter into insert mode in vim with the default configuration as well. It is the start of text object commands like `viw` or `vi{`

**Comment by sergeichestakov** [comment]
ahh you're right. my mistake, thanks!
