### ISSUE TITLE
Oversized cursor over tab characters in normal mode

### ISSUE THREAD

**Issue by sergeichestakov** [replit/codemirror-vim#109]
See title. Cursor becomes huge when moving it over a tab (`\t`) character. Repro is simple simply change the relevant part of the initial doc to the following and place your cursor over the tab characters in normal mode:

```javascript
const doc = \`
\t\tconsole.log('hi')
\`
```

See demo:
![oversized-cursor-vim-tabs](https://user-images.githubusercontent.com/24947334/232923943-bcdeb426-783f-4258-adfb-f15359199830.gif)

**Comment by nightwing** [comment]
Now it covers the entire character. Do you want it stay at one default character width?

**Comment by masad-frost** [comment]
Looks like the way vim handles it is by covering entire characters, but special casing `\t` to show the cursor at the end of the character.

Let's special case `\t` to show a single character width block cursor at the end of the tab, if it breaks the system and requires refactoring let us know.
