### ISSUE TITLE
Repl.it demo not working

### ISSUE THREAD

**Issue by lishid** [replit/codemirror-vim#11]
https://replit.com/@util/codemirror-vim

Hoping to use the demo as a bug testing ground, however I seem to just get a white box in there:

![image](https://user-images.githubusercontent.com/609710/164308214-0d97d91e-f924-4770-84f5-7d3875d8b470.png)

**Comment by sergeichestakov** [comment]
Ooof thanks! Not sure how that regressed but it seems to have been some mix up in dependencies. Should be working now. Fixed in https://github.com/replit/codemirror-vim/commit/e00785d60203419b18dc123ab7a6db81600df2ab
