### ISSUE TITLE
FR: full support of `{n,v,o,i}noremap`

### ISSUE THREAD

**Issue by chrisgrieser** [replit/codemirror-vim#112]
apparently, there is [some limited support for noremap](https://github.com/replit/codemirror-vim/blob/master/src/vim.js#L765), but I think full support of `noremap` would be very desirable.

There are a lot of common vim mappings like `nnoremap x "_x` that are currently not possible with `noremap`

**Comment by Archie-2021** [comment]
It is such a useful feature, hope to see it implemented soon.

**Comment by nightwing** [comment]
Turns out full support for noremap required less code than the limited one:)

**Comment by chrisgrieser** [comment]
thank you so much <3
