### ISSUE TITLE
Changing the color of the Normal Mode Cursor

### ISSUE THREAD

**Issue by rashadphil** [replit/codemirror-vim#119]
I'm trying to change the color of the Vim cursor from the default orange. I attempted to modify my CodeMirror theme by adding the following CSS, but it doesn't seem to be working properly:

```js
 ".cm-fat-cursor": {
 position: "absolute",
 background: "#ff0000",
 border: "none",
 whiteSpace: "pre",
 },
 "&:not(.cm-focused) .cm-fat-cursor": {
 background: "none",
 outline: "solid 1px #ff0000",
 color: "transparent !important",
 },
```

Is changing the cursor color possible?
Any advice you could offer would be greatly appreciated. Thanks!

**Comment by sergeichestakov** [comment]
how are you styling it? are you using a theme extension? if not, make sure you are and that it has a precedence of Highest like our [theme extension does](https://github.com/replit/codemirror-vim/blob/7e70ff7d321f9aa6600616a4d2ee81327394533a/src/block-cursor.ts#L129)

**Comment by rashadphil** [comment]
Hey Sergei, I'm using a theme extension with precedence of Highest. It seems like my CSS is being applied but the original theme takes precedence. I'm attaching an image of the CSS in my developer tooling.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/20783686/234761740-c6ba05b2-5d32-4fb3-aff5-9efb32bda0e5.png">

Here is the full code snippet that I've tried:
```js
const EditorTheme = Prec.highest(
  EditorView.theme({
    ".cm-fat-cursor": {
      position: "absolute",
      background: "#ff0000",
      border: "none",
      whiteSpace: "pre",
    },
    "&:not(.cm-focused) .cm-fat-cursor": {
      background: "none",
      outline: "solid 1px #ff0000",
      color: "transparent !important",
    },
  })
);
```

**Comment by sergeichestakov** [comment]
gotcha is it loaded before the Vim extension? because ordering is used to determine which to apply if precedence is the same.

this is not ideal but have you tried adding `!important` to the outline in your styling? we've generally had to do that when trying to style something that is already styled by an existing extension.

@nightwing do you know a way around this? I think we're going to want to make this configurable anyways perhaps as a config option

**Comment by rashadphil** [comment]
The ordering was my problem! Loading my theme before the vim extension fixed it. Thanks for the help!
