### ISSUE TITLE
Characters needing `AltGr` don't work in normal mode

### ISSUE THREAD

**Issue by kometenstaub** [replit/codemirror-vim#12]
In Vim mode, keyboard shortcuts such as `fx`, `tx`, `vix` don’t work if `x` is a character that requires pressing `AltGr`, such as `{[]}€@\` on the German keyboard layout.

Downstream Bug report: https://forum.obsidian.md/t/vim-mode-shortcuts-involving-altgr-dont-work/36211

I can reproduce the bug in both Firefox and Chromium on Linux in the playground: https://codemirror-vim--util.repl.co/

The behaviour is different for each key. For `{` it jumps a paragraph up, for `[` it activates the first of two `[[` presses, on the second it jumps to the top of the document. For `|`, it goes to the beginning of the line.

**Comment by kometenstaub** [comment]
I found the issue. The problem is that both `AltGr` and the converted key are sent. So on the keyboard it is `AltGr+8`, and codemirror receives (for the German locale) `AltGr` and `[`. Capturing and preventing `AltGr` fixes it.

**Comment by nightwing** [comment]
Does it work if you add AltGr to ignoredKeys at https://github.com/replit/codemirror-vim/blob/a2d37a01f68ee21a041f72c7272b3b4f9471cf7d/src/cm_adapter.ts#L74?

**Comment by kometenstaub** [comment]
Yes, it does.
