### ISSUE TITLE
Spellchecker replacement broken

### ISSUE THREAD

**Issue by lishid** [replit/codemirror-vim#124]
When using codemirror-vim with a browser spellchecker, choosing the correct replacement doesn't work.

I have bisected the issue to this commit https://github.com/replit/codemirror-vim/commit/5d29c9fca2082186fce77786b968a02cee218ab0

I believe the spellchecker correction action gets considered as an unknown key event and causes the change to get reverted.

To reproduce:
- Go to https://replit.com/@util/codemirror-vim
- Use developer console to swap `spellcheck="false"` to `spellcheck="true"`
- Attempt to replace a misspelled word

Video:

https://github.com/replit/codemirror-vim/assets/609710/3f6633ea-5bb7-4b84-b572-b430a71d9988

**Comment by Laharah** [comment]
I can confirm that this issue is affecting [obsidian](https://obsidian.md) downstream.

**Comment by thrawn01** [comment]
Here to add support for this bug. This issue is also affecting me.

**Comment by lishid** [comment]
Does not seem fixed, please reopen.

**Comment by nightwing** [comment]
Do you mean that the issue is reproducible on master branch (e.g. on https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html), or that the fix is not released to npm yet?

**Comment by lishid** [comment]
Sorry about that, I was testing on the replit site! Master seems to work.
