### ISSUE TITLE
Replacing a character (r) doesn't work with two-key characters (^+o = ô, etc.)

### ISSUE THREAD

**Issue by lebigot** [replit/codemirror-vim#125]
Replacing a character in normal mode with the "r" command doesn't work when the replacement requires multiple keys (such as ô on a French keyboard, which is obtained through typing `^` and then `o`).

The current behavior of codemirror-vim (in its version included in Obsidian 1.2.8 at least) is to insert the first key only (so `^`, in the example) and then to process the next keys (still in normal mode).

The current version of vim does work as expected.

Thanks!

**Comment by nightwing** [comment]
Does this work with vim itself? For me MacVim 9.0 also replaces with the first character, but maybe this behavior depends on flag, or maybe we should behave differently from vim in this particular case?

**Comment by lebigot** [comment]
vim on macOS does work as expected (you can replace a character with a character that uses ^). I'm not sure if it's the MacPorts or some macOS built-in version (I'm not close to my Mac).
