### ISSUE TITLE
Replacing a character doesn't work when using dead key

### ISSUE THREAD

**Issue by lebigot** [replit/codemirror-vim#132]
Replacing a character (in normal mode, with r) doesn't work when the replacement uses a dead key (for example, replacing with ë, when entered as ¨+e).

For example, in the demo at https://codemirror.net/5/demo/vim.html, typing ¨+e does nothing and the editor keeps waiting for a replacement character.

Thanks!

If this matters, I am using Mac French keyboard.

**Comment by nightwing** [comment]
Closing as duplicate of https://github.com/replit/codemirror-vim/issues/125
