### ISSUE TITLE
Undesirable behavior when cursor navigates wrapped line

### ISSUE THREAD

**Issue by ggsvr** [replit/codemirror-vim#133]
When a line gets too long and wraps around in the editor, moving the cursor up and down still treats the wrapped line as one, skipping the visually distinct lines. This does not happen with the default cursor.
The issue was observed in Obsidian, which uses this extension for vim support.
![vimcursor](https://github.com/replit/codemirror-vim/assets/57045797/af1aa8ce-f93c-42e3-84ab-e88ac0c5fa09)

**Comment by nightwing** [comment]
This is the way vim itself behaves, j skips line and gj works like a normal down arrow.

**Comment by firai** [comment]
You can install the https://github.com/esm7/obsidian-vimrc-support plugin in Obsidian to remap <kbd>j</kbd> to <kbd>gj</kbd>, <kbd>k</kbd> to <kbd>gk</kbd> and the reverse of the two pairs. This is a fairly common remapping in the vim/neovim world as well.

**Comment by nightwing** [comment]
Closing as this is the way vim is meant to behave.
