### ISSUE TITLE
escape key blurs codemirror instead of exiting insert mode

### ISSUE THREAD

**Issue by niwla23** [replit/codemirror-vim#138]
When I am in insert mode and press escape, I would expect it to go back to normal mode but instead the editor looses focus. I guess this is due to some browser defaults? Is there any way to fix this? I am using svelte-codemirror-editor.

**Comment by nightwing** [comment]
Maybe you have another codemirror extension that handles escape key before vim? Do you see the same issue on https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html?

**Comment by nightwing** [comment]
Did you manage to find the cause of the issue you were seeing? I am closing this due to lack of reproduction steps, but if you have any additional info, please comment.

**Comment by Dima-369** [comment]
I have the exact same issue happening, but it is indeed this issue: https://github.com/philc/vimium/issues/2734

If I disable the Vimium extension for the page in Firefox, Escape works as one expects to exit insert mode.

https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html
