### ISSUE TITLE
Repl.it demo auto resets every 20 seconds

### ISSUE THREAD

**Issue by WhiteNoiseDev** [replit/codemirror-vim#14]
https://replit.com/@util/codemirror-vim

The demo auto reset/refresh to its original state every 20 seconds making it unusable for testing.

Thanks

**Comment by sergeichestakov** [comment]
Thanks! Should be fixed by https://github.com/replit/codemirror-vim/commit/a2d37a01f68ee21a041f72c7272b3b4f9471cf7d
