### ISSUE TITLE
Insert mode maps don't support character insertion

### ISSUE THREAD

**Issue by tenmajkl** [replit/codemirror-vim#149]
When I have mapping `vim.map("aa", "á", "insert");` and write `aa` it doesn't paste `á` as expected. It only erases `aa` but doesn't write anything.

**Comment by tenmajkl** [comment]
This problem happens in overleaf and its the only place I've tested it, my bad. So its probably not updated there.

**Comment by nightwing** [comment]
Indeed, they have an old version that doesn't support `:normal` command too. Hopefully they will update it soon.
