### ISSUE TITLE
Up/Down arrow stop working for visual-block mode

### ISSUE THREAD

**Issue by cotemaxime** [replit/codemirror-vim#15]
Upgrading to 0.20 it looks like the up/down arrow stopped working for selection up/down lines in visual mode via Shift+V. 

The selection seems to reset itself and go back to normal mode at the end of the line when using up/down, but it works as expected using j/k. 

Repro steps are:
- shift+v to enter line selection
- up arrow

**Comment by nightwing** [comment]
This was fixed by the linked pull request. Thank you for the report.
