### ISSUE TITLE
[Question] Alter an operator

### ISSUE THREAD

**Issue by brendanbond** [replit/codemirror-vim#155]
I have application-level state, e.g. delimiter text that gets parsed and replaced with a widget, that may require vim operators to be aware of it and modify things like ranges, heads, and anchors accordingly. However, the CM5 Vim API would force me to reimplement the operators rather than be able to hook into their lifecycle and modify their parameters, and I don't think the library exposes the operators directly.

Would there be any appetite for a PR that addresses this by adding an `alterOperator` interface that would allow a user to pass an intermediate function that returns a new set of parameters and then calls the operator method? Something like

```javascript
function defineOperator(name, fn) {
  operators[name] = fn;
}

function alterOperator(name, fn) {
  if (operators[name]) {
    const oldFn = operators[name];
    operators[name] = function(cm, prevArgs, prevRanges, prevOldAnchor, prevNewHead) {
      const { args, ranges, oldAnchor, newHead } = fn(cm, prevArgs, prevRanges, prevOldAnchor, prevNewHead);
      return oldFn(cm, args, ranges, oldAnchor, newHead);
    };
  }
}
```

I'm pretty new to CM and this library, so apologies if there's a much more obvious way to accomplish something like this.

**Comment by nightwing** [comment]
Could you tell a bit more about your usecase, and show what the fn function is meant to do.

I am worried that alterOperator above would expose too much internal details in public api, but maybe i am wrong, or maybe we can work together to find a better/easier to maintain api for your usecase.

**Comment by brendanbond** [comment]
Thanks @nightwing! Sure - the idea is that the application uses delimiter text (with the grammar `"\n<delemiter>\n"`) that is parsed and replaced with a widget to implement a "block" system:

```
this is a block, the line below is delimiter text that will be replaced with a visual widget (e.g. a styled horizontal line)
∞∞∞markdown
here is another block
```

When I use the backspace key to delete line 3 (if I was in insert mode), the widget is removed and the cursor moves to the end of line 1:

```
this is a block, the line below is delimiter text that will be replaced with a visual widget (e.g. a styled horizontal line)
```

But if I were in normal mode and used the 'dd' linewise delete operator, we blow up the delimter grammar by removing the second newline character, and the delimter text is no longer parsed and replaced and is visible to the user:

```
this is a block, the line below is delimiter text that will be replaced with a visual widget (e.g. a styled horizontal line)
∞∞∞markdown
```

The same is true for operators like `d/m` or `:%s/markdown/javascript/g`. Rather than completely reimplement operators to be "aware" of the delimiter text, it would be kind of nice to introduce the ability to add offsets to the range arguments passed to the operators:

```
    // psuedocode
    Vim.alterOperator('delete', function(cm, prevArgs, prevRanges, prevOldAnchor, prevNewHead) {
        let state = editor.view.viewState.state;
        const doc = state.doc;
        const cm6Ranges = prevRanges.map((range) => convertToCM6Range(range.anchor, range.head, doc));
        const activeBlock = getActiveNoteBlock(state);
        let newRanges = prevRanges;
        if (cm6Ranges.contains(activeBlock.delimiter)) {
            newRanges = addDelimiterOffset(prevRanges, activeBlock.delimiter);
        }

        return {args: prevArgs, ranges: newRanges, oldAnchor: prevOldAnchor, newHead: prevNewHead};
    });
```

I didn't want to start implementing this without knowing if there was any appetite for this type of API, so this obviously could be cleaned up quite a bit (e.g. I don't like returning an object of args). Let me know if you have any thoughts/suggestions!

**Comment by nightwing** [comment]
Wouldn't it be simpler to use codemirror's [EditorState.changeFilter](https://codemirror.net/docs/ref/#state.EditorState^changeFilter) api to prevent changes from destroying blocks? That way just one function should be able to handle all the cases, instead of having to call alterOperator on unknown number of operators and having to change your code when vim mode implements some new commands that are able to delete text?

**Comment by brendanbond** [comment]
It's funny you mention this because, after my inquiry this morning, I was looking at just such a solution. Thanks for the info! I'll close this for now
