### ISSUE TITLE
Ctrl-[ does not act as escape

### ISSUE THREAD

**Issue by byronclark** [replit/codemirror-vim#16]
Issue: Instead of acting as an escape key, Ctrl-[ decreases the indent level.

Observed in:
- The replit demo: https://replit.com/@util/codemirror-vim in Firefox
- [Obsidian](https://obsidian.md/) after the recent update to CodeMirror 6 (I believe this uses codemirror-vim, but I'm not entirely sure)

As far as I can tell this only happens on Linux and Windows. MacOS is unaffected.

**Comment by byronclark** [comment]
I see that the binding is present in the code: https://github.com/replit/codemirror-vim/blob/master/src/vim.js#L76

**Comment by byronclark** [comment]
I believe the issue is that the key is overridden by the CodeMirror defaultKeyMap which is usually loaded after starting `vim()`.

https://github.com/codemirror/commands/blob/main/src/commands.ts#L876
```
  {key: "Mod-[", run: indentLess},
  {key: "Mod-]", run: indentMore},
```

**Comment by nightwing** [comment]
This was fixed by the linked pull request. Thank you for the report.
