### ISSUE TITLE
 WS-2472: Find-backwards <Space> ignored

### ISSUE THREAD

**Issue by blast-hardcheese** [replit/codemirror-vim#163]
`f<Space>` searches forward to the next space, `F<Space>` should search backwards as well.

**Comment by nightwing** [comment]
This is already implemented, could you please check if you see the issue on https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html? Maybe there is a bug for specific text, or a browser, so more detailed reproduction steps would be greatly appreciated.

**Comment by blast-hardcheese** [comment]
Here's a screen recording:
https://github.com/replit/codemirror-vim/assets/278900/705c38bd-4965-44cc-a86f-4a0ca7e4d9bf

Keys pressed:
```
<Return><Return>f<Space>f<Space>f<Space>F<Space>F<Space>F<Space>
```

I expected to go down two lines (✅) skip forward three instances of ` ` (✅) skip backwards two instances of ` ` (❌, only two here because there wouldn't be a third, the cursor would end at the first ` ` in the line)

Browser: Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (arm64)
OS: macOS Sonoma, 14.2.1 (23C71)

Also tested on Safari, unexpected behavior there as well.

**Comment by nightwing** [comment]
Which keyboard layout do you use?

**Comment by blast-hardcheese** [comment]
@nightwing `U.S.`
<img width="476" alt="image" src="https://github.com/replit/codemirror-vim/assets/278900/11e374dd-38bc-4894-9d95-1ad84b14ca49">
<img width="827" alt="image" src="https://github.com/replit/codemirror-vim/assets/278900/df5c14ff-fa93-4d82-9994-02f0585988f0">

**Comment by nightwing** [comment]
I have added input event logging to the demo here https://raw.githack.com/replit/codemirror-vim/input-log/dev/web-demo.html could you please try running the same input on that page and show what is printed to the log section.

Here's what i get with same settings as you

https://github.com/replit/codemirror-vim/assets/341801/60326c38-de2b-45b9-adb9-8441ec9eb1db

.

**Comment by blast-hardcheese** [comment]
🤯 I realized, the issue is CM thinks that `<Shift><Space>` is different than `<Space>`, but vim does not. My muscle memory has been to just keep shift down, only when looking at your character log, `<Space>` in yours vs `<S-Space>` in mine:

https://github.com/replit/codemirror-vim/assets/278900/0cd098a6-854b-49d2-8e8d-2bec17c6d35a

Sorry for not realizing the actual issue here earlier, I'm glad it's not something more esoteric!
