### ISSUE TITLE
CM default indent/dedent of Cmd + Square Brackets is not suppressed when vim is the chosen flavor

### ISSUE THREAD

**Issue by blast-hardcheese** [replit/codemirror-vim#168]
Good day! The behavior I'm seeing here is that the default indent/dedent shortcut is left as a fallback to the vim binding of `^d`/`^t`. I've verified this behavior in https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html, with a video demo below to go along with my repro steps:

1. Observe that in normal mode, `Command+[` or `Command+]` incorrectly dedent or indent
2. Switch to insert mode
3. Observe that `^d` and `^t`

---

![cm vim](https://github.com/replit/codemirror-vim/assets/278900/8a85b781-c165-4638-919a-389d04fc0ed0)

**Comment by nightwing** [comment]
I think allowing fallback to default codemirror behavior for all shortcuts that are not handled by vim was intentional design choice of the original cm5 vim mode. In which usage scenarios does this create any problems?

**Comment by blast-hardcheese** [comment]
The problem is one of usability -- `Cmd+[`/`Cmd+]` are the system bindings for Navigate Back/Navigate Forward, so by having the fallback from vim to the standard bindings, I not only have have two ways to do the same thing, but I also can't use the standard OS bindings for navigating forwards and backwards.

What would be ideal, though it may not be easy to do, is to only fall back to the standard keybindings for operations that do not have a vim-mode binding.

**Comment by masad-frost** [comment]
> I think allowing fallback to default codemirror behavior for all shortcuts

I think this makes sense from the library's perspective. Will close the issue out.

I think this is about how we configure our editor, on replit.com, we can probably remove the default keybindings when we use the vim keybindings. I remember we added the defaults for some reason, we can investigate.
