### ISSUE TITLE
Ctrl-D no longer pages down

### ISSUE THREAD

**Issue by insanum** [replit/codemirror-vim#17]
Ctrl-D now deletes the character under the cursor instead of paging down.

**Comment by byronclark** [comment]
Interesting, that's the emacs keybinding for Ctrl-D. Since that's part of the defaultKeymap for CodeMirror it's probably overriding what is set by codemirror-vim. I think it's the same cause as #16.

**Comment by dev-msp** [comment]
Maybe unrelated (or also shares a cause with #16), but Backspace now deletes the previous character in normal mode, instead of just moving the cursor.

**Comment by nightwing** [comment]
This was fixed by the linked pull request. Thank you for the report.
