### ISSUE TITLE
`j` in visual mode renders offset to actual line when there is empty lines

### ISSUE THREAD

**Issue by zzhixin** [replit/codemirror-vim#171]
### Description
If there is empty lines, in visual mode, the cursor renders one line offset to the actual line.
![codemirror-vim](https://github.com/replit/codemirror-vim/assets/40470855/10c8b062-0406-42ab-b15c-d17e00834292)

### Expected behavior
In the gif above, after pressing `j`, the cursor should be at the second line rather than the end of the first line. After pressing 2x`j`, the cursor should be at the third line rather than the second line. 

Although the cursor get right after pressing 3x`j`, the behavior is weird that the cursor goes 2 lines downward at the last `j` stroke.

### Reproduce
1. Open [sandbox](https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html)
2. Delete default content, enter 
```
This is a test.


This is another test.
```
3. press `ggVjjj`.

### Comment
What is interesting is that in codemirror5, no such bug.

**Comment by firai** [comment]
Hi @nightwing and @sergeichestakov, thanks for fixing this! I'm not sure whether you are waiting for any other PRs to be merged first, but would it be possible to release a version that incorporates the fix?

**Comment by sergeichestakov** [comment]
yes! apologies for the delay. @masad-frost should be able to help. I'm no longer a member of the org.

**Comment by firai** [comment]
Hi @masad-frost, would it be possible for you to release a new version, unless you're waiting for certain PRs to be merged first? Thanks for your help!
