### ISSUE TITLE
The /g flag on :s in Vim mode doesn't work as it should - it only replaces the first occurrence

### ISSUE THREAD

**Issue by masad-frost** [replit/codemirror-vim#173]

**Comment by nightwing** [comment]
Could you tell more details about the reproduction steps.

On https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html if i do 

```
:2
:s/i/x/g
``` 

all `i`s are replaced as expected

**Comment by masad-frost** [comment]
@cdmistman reported this, can you provide more info?

**Comment by cdmistman** [comment]
hmmmmm, i'm unable to repro now. apologies!
