### ISSUE TITLE
@codemirror/view@6.28.4 + Chrome v126 - Enter not inserting new line in insert or normal mode

### ISSUE THREAD

**Issue by infime** [replit/codemirror-vim#182]
Seems likely to have something to do with the new EditContext API usage (https://github.com/codemirror/view/blob/ed78a0cbb6852c02acc93c85cbabe0ac12ab13c1/CHANGELOG.md#new-features).

Still works as expected on 6.28.1 + Chrome v126

**Comment by nightwing** [comment]
Do you see this on https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html, or with another configuration? I couldn't reproduce the bug with chrome 126 on windows with the above link.

**Comment by nightwing** [comment]
@infime did you include [basicSertup](https://codemirror.net/docs/ref/#codemirror.basicSetup), or https://codemirror.net/docs/ref/#commands.standardKeymap in your codemirror setup? Seems like the change is in codemirror itself which does not insert new lines without standardCommands if  EditContext mode is active.
