### ISSUE TITLE
Visual mode: arrow keys do not select text

### ISSUE THREAD

**Issue by dpecos** [replit/codemirror-vim#183]
When in visual mode, I can select using h/j/k/l but not with the arrow keys.

In fact, if I start the selection with h/j/k/l and then I press any of the arrow keys, the selection disappears.

In any case the arrow keys are moving the cursor, the issue is only with the selection.

**Comment by dpecos** [comment]
That demo works fine. 

Thx for the tip on plugin precedence, I'll play with the order of the plugins and will let you know which one was the culprit.

**Comment by dpecos** [comment]
Found it! By mistake I was loading the `defaultKeymap` and vim's.

Loading just vim's fixed the issue, obviously.

Thx for pointing me in the right direction.

**Comment by nightwing** [comment]
you need to include the default keymap too, in order for insert mode to work, just include it after vim

**Comment by dpecos** [comment]
I just figure out exactly that, but the hard way :-S
