### ISSUE TITLE
Mappings for Arrow Keys

### ISSUE THREAD

**Issue by SBrazzCode** [replit/codemirror-vim#185]
In VIM the arrows keys perform just like hjkl, so 7j is the same as 7↓. This doesn't seem to work with this extension. I tried to just add mappings too, but something like `Vim.map("↓", "j")` doesn't work.

**Comment by nightwing** [comment]
Arrow keys are implemented as mappings to hjkl https://github.com/replit/codemirror-vim/blob/160a7fdbf25f17eede87e75e04b3874b73ac8a41/src/vim.js#L76 

Maybe something in your browser or codemirror setup overrides the default behavior of codemirror-vim.

Do you see this issue on raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html

**Comment by SBrazzCode** [comment]
> Arrow keys are implemented as mappings to hjkl
> 
> https://github.com/replit/codemirror-vim/blob/160a7fdbf25f17eede87e75e04b3874b73ac8a41/src/vim.js#L76
> 
> Maybe something in your browser or codemirror setup overrides the default behavior of codemirror-vim.
> 
> Do you see this issue on https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html ?

You're right sorry. The mappings work in the demo, so it must be my setup.
