### ISSUE TITLE
Ctrl+A doesn't increment the number

### ISSUE THREAD

**Issue by tadashi-aikawa** [replit/codemirror-vim#20]
Thank you for the great plugin :)

I found a bug that `Ctrl+A` doesn't increment the number. On the other hand, `Ctrl+X` works correctly.

https://user-images.githubusercontent.com/9500018/174708077-cd0fa532-f15c-4563-aff7-5bf224e52805.mp4

Best regards.

**Comment by nightwing** [comment]
This was fixed by the linked pull request. Thank you for the report.

**Comment by tadashi-aikawa** [comment]
Thanks a lot 😄
