### ISSUE TITLE
Ctrl+I doesn't work as expected

### ISSUE THREAD

**Issue by tadashi-aikawa** [replit/codemirror-vim#21]
Cited from Vim official help.

> 							*jumplist*
> Jumps are remembered in a jump list.  With the CTRL-O and CTRL-I command you
> can go to cursor positions before older jumps, and back again.  Thus you can

https://user-images.githubusercontent.com/9500018/174709130-a88d44e7-bd97-454c-9eb2-539434dd1770.mp4

**Comment by nightwing** [comment]
This was fixed by the linked pull request. Thank you for the report.

**Comment by tadashi-aikawa** [comment]
Thanks a lot 😄
