### ISSUE TITLE
Yanking And Pasting From System Clipboard

### ISSUE THREAD

**Issue by Archie-2021** [replit/codemirror-vim#29]
Can you please make `"+y` or `*+y` and `"+p` or `*+p` available, it is very important and basic command and yet not implemented from vim. I know there a command to tell the vim use system clipboard. But vim mess with clipboard a lot so it is better imo to not to do that and instead use a different command for that. 

thanks

**Comment by nightwing** [comment]
Browsers do not provide access to the selection clipboard so * can't work correctly. Should it be an alias for +, or should it just stay unimplemented?

**Comment by kometenstaub** [comment]
I think it should stay unimplemented. In Windows an alias might make sense because they're the same clipboard, but not on Linux (and macOS; not 100% sure about that).

**Comment by ianhi** [comment]
Some discusison of this in the past here: https://github.com/codemirror/codemirror5/issues/3075

I also found that as a consumer of the vim API you can add yanking to the system clipboard with these two snippets:

https://github.com/ianhi/jupyterlab-vimrc/blob/2dedaf7f48b7b3bd462defda77ae3865fbff70e9/src/index.ts#L34-L37
https://github.com/ianhi/jupyterlab-vimrc/blob/main/src/yank.ts

**Comment by Archie-2021** [comment]
> Some discusison of this in the past here: [codemirror/codemirror5#3075](https://github.com/codemirror/codemirror5/issues/3075)
> 
> I also found that as a consumer of the vim API you can add yanking to the system clipboard with these two snippets:
> 
> https://github.com/ianhi/jupyterlab-vimrc/blob/2dedaf7f48b7b3bd462defda77ae3865fbff70e9/src/index.ts#L34-L37 https://github.com/ianhi/jupyterlab-vimrc/blob/main/src/yank.ts

i think this just set the clipboard to unnamed which i already use to solve the issue, but sometimes there is an app without any vimrc file to put it in, so a easier why to make copy pasting available is needed. i mean what is more important than that? i like to use vim everywhere i can find a plugin for it and many of them use code mirror to emulate it.

**Comment by nightwing** [comment]
Closing since the + register works now, if there are additional feature requests please create a new issue.

**Comment by llinfeng** [comment]
Is there a way to use a Userscript to yank to the clipboard with `<c-c>`, @nightwing? It seems Overleaf hasn't implemented the new `+`-registry patch yet.

**Comment by kometenstaub** [comment]
It's a very simple implementation, see this comment: https://github.com/replit/codemirror-vim/pull/36#issuecomment-1186192936

**Comment by llinfeng** [comment]
@kometenstaub Thanks for the pointer. Though, from an end-user perspective, are you suggesting that I should find a way to edit /replace/override the `vim.js` file according to your commit, [as linked](https://github.com/replit/codemirror-vim/pull/36/files)? Then, I assume I should find a way to load [this file](https://raw.githubusercontent.com/kometenstaub/codemirror-vim/fd750b6b8787c8f5809eda40f662f50be9a208e7/src/vim.js) from your commit?

**Comment by kometenstaub** [comment]
I’m not suggesting anything, I just meant that it isn’t possible right now and someone would need to implement it.

**Comment by llinfeng** [comment]
I see. Thanks for the clarification.
