### ISSUE TITLE
Hard freeze when using regex search and emoji

### ISSUE THREAD

**Issue by WhiteNoiseDev** [replit/codemirror-vim#32]
1. Open https://codemirror-vim--util.repl.co/
2. Replace text with emoji 🌞
3. In Normal mode, press `?` and then `^` for regex search
4. Observe Tab Freeze and high cpu usage.

It doesn't happen in CM5.

**Comment by nightwing** [comment]
This is a bug in search functionality of codemirror 6 itself https://github.com/codemirror/dev/issues/926
