### ISSUE TITLE
Inserting unwanted characters when scrolling with j or k, Linux fcitx-skk/ibus-skk

### ISSUE THREAD

**Issue by ka2n** [replit/codemirror-vim#34]
Although it is rare, when the editor is in normal mode, moving around with `j`, `k`, `w`, etc., actually results in `j`, `k`, `w`, etc., being entered as text.
This occurs frequently when the host application is running slow.

It occurred on Linux when using the input methods `fcitx-skk` or `ibus-skk`; it did not occur when using direct alphabetical input with ibus.

Note that I could not reproduce the problem with https://codemirror.net/demo/vim.html.

- OS: `Linux junior 5.18.10-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 07 Jul 2022 17:18:11 +0000 x86_64 GNU/Linux`
- Window Manager: `i3 version 4.20.1 (2021-11-03)`
- Input Method: `IBus 1.5.26`, `ibus-skk 1.4.3`

https://user-images.githubusercontent.com/427686/179142165-306d2ee0-1a3b-4880-ac9e-c6b79dc5cb88.mp4

**Comment by WhiteNoiseDev** [comment]
This happens on OSX too.

**Comment by nightwing** [comment]
Should be fixed by the linked pull request
