### ISSUE TITLE
S behaves strangely in normal mode

### ISSUE THREAD

**Issue by nicholasbulka** [replit/codemirror-vim#4]
First wanted to say thanks for undertaking this large project. If I can help, please let me know how.

I noticed "S"  was behaving a little strangely in normal mode:

Expected behavior: insert starting from the first character in the line
Actual behavior: insert mode starting from the 0 position of the line.

**Comment by llinfeng** [comment]
Has this been fixed already? I tested `S` in normal mode on Overleaf, which uses CodeMirror v6(?), and it deletes the whole line as expected and puts the cursor at the start of the line.

**Comment by nightwing** [comment]
Looks like this was fixed on codemirror side for most situations, but in cases when user doesn't like the automatic indentation, the  behavior is a bit annoying.

@sergeichestakov should we change `S` to exactly match vim behavior, which is to leave indentation of current line unchanged independently of autoindent?

**Comment by nightwing** [comment]
I am not sure about the exact reason, the current code was introduced in  https://github.com/codemirror/codemirror5/commit/c78d76c829b770aed68c71383960a7b6195e831b, but it was buggy https://raw.githack.com/codemirror/codemirror5/c78d76c829b770aed68c71383960a7b6195e831b/demo/vim.html, and i can't find any discussion about intentionally making the behavior to differ from vim. So i guess it is better to change this.

**Comment by sergeichestakov** [comment]
ahh ok yeah let's do it then
