### ISSUE TITLE
Error using with Sandpack

### ISSUE THREAD

**Issue by SpencerDuball** [replit/codemirror-vim#57]
`Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.`

I dealt with an issue trying to get `@codesandbox/sandpack-react` to work with `@replit/codemirror-vim` recently, this was due to a mismatch of the `@codemirror/state` component (which happens when extensions have mismatching versions of this package). In this case it looks like `@replit/codemirror-vim` has a more up-to-date version than the latest `@codesandbox/sandpack-react`. To fix this issue in the meantime you can install:

```bash
npm i @replit/codemirror-vim@0.19.1
```

This is the last compatible version with the current instance of sandpack, the version I am using is: `@codesandbox/sandpack-react": "^1.15.1"`.

This is NOT an issue with this package, but took me a good amount of looking to find the solution and this issue exists to save people some time in the meantime.

**Comment by SpencerDuball** [comment]
Closing as this is resolved, the mismatch is because sandpack has a less up-to-date package of codemirror. Hope this issue saves someone time in the future.

**Comment by sergeichestakov** [comment]
awesome, thanks for the update!
