### ISSUE TITLE
Copying With Ctrl+c Does Not Work

### ISSUE THREAD

**Issue by Nesaijn** [replit/codemirror-vim#59]
I would like to open the long standing issue of Ctrl+c not working to copy mentioned here: https://github.com/codemirror/codemirror5/issues/3075

Reason for Ctrl+c not working seems to be that it is mapped to exit insert mode. This seems to also grab when not in insert mode.

**Comment by nightwing** [comment]
Ctrl-c is supposed to exit visual mode too.
As a workaround we could allow ctrl-c to be handled by browser when exiting visual mode.
And clear selection in insert mode instead of exiting.
@sergeichestakov what do you think?

**Comment by sergeichestakov** [comment]
Yeah that sounds reasonable to me. I'm in favor of deferring to the browser for `Ctrl-c`, at least in normal mode. I also find it frustrating that that doesn't copy the selected text
