### ISSUE TITLE
How to programmatically change modes?

### ISSUE THREAD

**Issue by jsjoeio** [replit/codemirror-vim#6]
Let's say I have a CM instance with text. User changes text in insert mode. I then update the value in CM editor and want to change the mode from insert to normal mode, how do I do that? 

Here's a demo:

![vim-demo](https://user-images.githubusercontent.com/3806031/148696097-361aef43-b9e8-400d-98e2-f32e96f331b4.gif)

I want to change to normal mode after the answer is correct. I'm not sure exactly how to do that. Can I call a method or something on CodeMirror and tell it to change modes?

**Comment by nightwing** [comment]
There is no cm6 style api, but you can use the old cm5 api 

```js
import {Vim} from "@replit/codemirror-vim"

var view = new EditorView({...})
Vim.exitInsertMode(view.cm)
```

or 

```js
Vim.handleKey(_view.cm, "<Esc>")
```

**Comment by jsjoeio** [comment]
Hmm...I must be missing something. TypeScript says that `.cm` does not exist on `view`. What am I doing wrong?

![image](https://user-images.githubusercontent.com/3806031/148856742-02bf3204-c414-4cc9-ad64-3474279ed8e5.png)

https://codesandbox.io/s/cm6-vim-test-mq5m9?file=/src/index.ts

**Comment by nightwing** [comment]
You are right. `cm` property exists on the js object, and in typescript can be used with a hack like `(view as any).cm`. 

I am not sure what can we do to extend the `EditorView` in a way that would not break type system.

Maybe we should export `getCm(view: EditorView): CodeMirror|null` function similar to https://codemirror.net/6/docs/ref/#search.getSearchQuery

**Comment by jsjoeio** [comment]
Hooray! That worked. Thank you. I like the idea of having a hook called `getCm` where you pass in an `EditorView`. 

That sounds nice.

Thank you very much for the two solutions and the fast reply.

**Comment by nightwing** [comment]
fixed in https://github.com/replit/codemirror-vim/commit/1ad745316b6987e0569d46a5d67c0263191d63af

**Comment by jsjoeio** [comment]
@nightwing when will you publish a new version with these changes? (may I suggest [this](https://jstools.dev/npm-publish/))

**Comment by sergeichestakov** [comment]
Thanks @jsjoeio! Just published an update to the NPM package with the above commit included. Feel free to upgrade to `v0.19.0-beta.7` and let us know if something's not working!

**Comment by jsjoeio** [comment]
Will do - thank you @sergeichestakov!
