### ISSUE TITLE
Global delete

### ISSUE THREAD

**Issue by x1101** [replit/codemirror-vim#62]
Global delete does not work in editors that implement codemirror-vim. This is reproducible in editors that include it, using [this demo](https://codemirror.net/5/demo/vim.html) and [this demo](https://codemirror-vim--util.repl.co/).

In all cases, global search returns the expected result, but when a delete command is added, it fails. 

**Steps to reproduce**
Using vim-mode for editing, in a file containing a list of completed tasks (markdown syntax)
```
- [x] Task
```
execute `:g/^-\s\[x\]/d`

**Expected result**
Matching lines are deleted

**Actual result**
`:43d` not an editor command (line number changes based on file, result does not).

**Comment by x1101** [comment]
None of the tests I'd posted show this as working. I still get the same "not and editor command" when I try to add the delete onto my global command. 

I tested this with using the "Run on Replit" link right from the npmjs page.

**Comment by nightwing** [comment]
Sorry for the confusion. The issue was closed because the pull request was merged, but the fix was not published to npm. It will be included in the next version that should be published soon.

**Comment by sergeichestakov** [comment]
hey @x1101 just published the above commit in `6.0.5`. Please give that a try and let us know if it's still not working!

**Comment by x1101** [comment]
I am unsure if the various demos have been updated, but as of today (2/10/23)

- [This one](https://codemirror.net/5/demo/vim.html) still gives the same error
- [This one](https://codemirror-vim--util.repl.co/) seems to be working

That leads me to believe that the issue has been fixed, and now I'm just waiting for downstream apps to pull changes. 

Thank you for addressing this!

**Comment by x1101** [comment]
Adding a follow up that the specific application I had issues with has now successfully integrated this change, and works as expected. 

Thank you for addressing this, it simplifies several workflows for me!
