### ISSUE TITLE
Visual modes do not highlight selection

### ISSUE THREAD

**Issue by adam-olema** [replit/codemirror-vim#63]
Visual modes appear to work, but there is no highlighting or any other visual clue (other than in the status bar) when using it, so it is easy to get an unexpected selection.

Is there some kind of styling that needs to happen?

**Comment by nightwing** [comment]
Do you see this issue on the example page from this repo or in your project?

If the second, make sure that drawSelection addon of codemirror is included https://codemirror.net/docs/ref/#view.drawSelection

**Comment by adam-olema** [comment]
This was indeed the issue and adding the extension fixed my problem.  I might have missed it, but I didn't see this described anywhere.  May I suggest adding this to your readme?  I would never have known about that addon if you hadn't mentioned it.
