### ISSUE TITLE
Multi-byte unicode issue for "blink on" cursor (e.g. for emoji)

### ISSUE THREAD

**Issue by zefhemel** [replit/codemirror-vim#68]
When using a multi-byte unicode character and the cursor blink is active I see a [?] overlayed, this is not expected:

<img width="64" alt="CleanShot 2022-12-15 at 14 32 12" src="https://user-images.githubusercontent.com/59073/207871901-f1ac23cd-936d-45db-b956-df8ab571a7b4.png">

In this case I used a 👧 emoji. Can be replicated easily e.g. here: https://replit.com/@util/codemirror-vim

**Comment by nightwing** [comment]
@sergeichestakov this have been fixed in https://github.com/replit/codemirror-vim/pull/49 but is not released to npm yet, could you update the npm package?

**Comment by sergeichestakov** [comment]
yep, thanks! published the fix in `6.0.4`!

**Comment by zefhemel** [comment]
Confirmed, this fixed it. Thanks!

**Comment by sergeichestakov** [comment]
awesome, great to hear!

@nightwing was just double checking this works and it seems to in most cases but it looks like some emojis, for example, ✈️, are still behaving weirdly and are treated as two characters. here's an example:

![cm-vim-emoji-demo](https://user-images.githubusercontent.com/24947334/207915986-f815f724-a274-49f8-9f3a-f8fc55fe7a40.gif)
