### ISSUE TITLE
Cursor not visible in insert mode

### ISSUE THREAD

**Issue by jsjoeio** [replit/codemirror-vim#7]
I am not sure if this is a bug or not (could be related to the theme) but when you're in insert mode, you can't see the cursor.

## Normal Mode

![image](https://user-images.githubusercontent.com/3806031/148858241-a815fe21-b629-4182-b7a6-8cbb36fc8558.png)

## Insert Mode

![image](https://user-images.githubusercontent.com/3806031/148858261-d27aa168-a0ad-4953-9724-27fa25fb5a42.png)

**Comment by nightwing** [comment]
Is [https://codemirror.net/6/docs/ref/#view.drawSelection](drawSelection) plugin included in the config? (It is included in the `basicSetup`).

**Comment by jsjoeio** [comment]
Oops, no. It is not. (I'm also not including `basicSetup` but I guess I should). Thank you!
