### ISSUE TITLE
International keyboard fix for opt-[key]

### ISSUE THREAD

**Issue by kometenstaub** [replit/codemirror-vim#71]
I think I found a fix for enabling things like `ci[` on macOS international keyboards.

I logged the keyboard events to the console in the adapter. 

<img width="409" alt="image" src="https://user-images.githubusercontent.com/83140328/209319937-d45ddeb9-663d-4bc2-bea3-4600830bd037.png">

When I press `opt`, it is of type `keydown` and not `keypress`.

![image](https://user-images.githubusercontent.com/83140328/209319757-b08d1dcb-ef52-45d7-8c38-d087c42370f4.png)

I changed it in this line:

https://github.com/replit/codemirror-vim/blob/66891bcbdc6c958fa37bc9cef57bcec248bc4d29/src/cm_adapter.ts#L202

<img width="532" alt="image" src="https://user-images.githubusercontent.com/83140328/209320189-f843f9ae-23a0-429f-b8e6-050b694ceb07.png">

Then I ran `npm run dev` and tested it in the browser, now combos like `ci{` or `va[` work for me.

I tested it with both German and French locale on macOS. It also works with combos that require shift, like `opt-shift-5` for French, which is used for `[`.

**Comment by kometenstaub** [comment]
Related to #56 and #60.

**Comment by kometenstaub** [comment]
Is there any news on this?

**Comment by sergeichestakov** [comment]
thanks for following up. @nightwing can you please take a look?

in the meantime, feel free to open a PR if you've identified the fix!

**Comment by nightwing** [comment]
Applying this change would disable all keybindings with `<A-`, while we do not have any of these by default, some users may have them defined as custom mappings.

The `e.type == "keypress"` check was introduced in https://github.com/replit/codemirror-vim/pull/60 in attempt to keep `<A-` events working as before and also to send an event with the special key, and while it fixed some of the cases, the extra events are breaking key combinations.

Considering that gvim itself doesn't support `<A-` syntax on mac, and it only works on linux i think we should change keypress check to navigator platform check on mac, i will make a pull request for this shortly.

**Comment by kometenstaub** [comment]
Thank you! :)
