### ISSUE TITLE
Building locally does not work

### ISSUE THREAD

**Issue by Alex23rodriguez** [replit/codemirror-vim#73]
Getting the minimal example described on the README works when installing the pacakge from npm works fine. But cloning the repo, building it, and then importing it using 
```
{  
  "dependencies": {
    "@replit/codemirror-vim": "file:../codemirror-vim",
    "codemirror": "^6.0.1"
  }
}
```
doesn't work: it causes the following error when run:
```
Uncaught Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
    inner index.js:2017
    inner index.js:1992
    inner index.js:1992
    flatten index.js:2021
    resolve index.js:1929
    create index.js:2756
    EditorView index.js:6295
    setupEditor editor.ts:9
    <anonymous> main.ts:21
```

This happens for both the latest commit (66891bc) as well as the `6.0.4` commit (2c5931f).

Any tips on how I should be building / what I am doing wrong?

**Comment by nightwing** [comment]
What  bundler are you using, most likely it is loading codemirror files both from your node_modules and node_modules from codemirror-vim. `vite` seems to work fine with the setup you are showing.

**Comment by Alex23rodriguez** [comment]
I am indeed using vite (`npm create vite@latest` with vanilla js).
I thought that too, but what's funny is it seems to have no issue with the package from npm, which i guess should be compiled the same way.
The codemirror repo i'm compiling with `npm run build` which uses rollup I think

**Comment by green-john** [comment]
I'm facing this same issue while using this plugin with Elixir's Phoenix. I think the conclusion that it is due to how modules are loaded is right, but how can I fix it?

**Comment by nightwing** [comment]
Most likely you can delete node_modules in codemirror-vim or tweak the package.json.

Unfortunately i was not able to reproduce the issue with the package.json from the top comment. But I can take another look if you give me the exact commands to replicate the issue, (or share a workspace demonstrating the issue  using an online ide).

**Comment by nightwing** [comment]
When trying to use npm workspaces, I have found that for vite this is caused by bundler itself not supporting symlinks, and adding `resolve: { preserveSymlinks: true }` to the config fixes the issue https://github.com/vitejs/vite/issues/11657#issuecomment-1385932066

esbuild also has several bug reports about symlinks not being followed, so i believe this is not an issue with codemirror-vim, but with the bundlers themselves
