### ISSUE TITLE
How do I write vim-latex like custom key bindings into the Overleaf (Codemirror) editor?

### ISSUE THREAD

**Issue by dabingougou** [replit/codemirror-vim#75]
I am aware that Tampermonkey (https://www.tampermonkey.net/) could potentially do this. For example, the first block shown below works, but the second doesn't. 

`
// ==UserScript==
// @name         Overleaf Editor Custom VIM Keybindings
// @namespace    http://tampermonkey.net/
// @version      0.1
// @match        https://www.overleaf.com/project/*
// @grant        none
// ==/UserScript==

(function() {
'use strict';

window.addEventListener("UNSTABLE_editor:extensions", (event) => {
const { CodeMirror, CodeMirrorVim, extensions } = event.detail;

// add custom keybindings - insert mode applies on insert
CodeMirrorVim.Vim.map("jj", "<Esc>", "insert"); 
`

This (the above) works fine but the below doesn't. How can I write these bindings into, say, a userscript for Overleaf? 

'
//    CodeMirrorVim.Vim.map("kk", "Right-Right", "insert");
//    CodeMirrorVim.Vim.map("ECI", "\\cite{<++>}<++>", "insert");
//    CodeMirrorVim.Vim.map("aa", "<Down>", "insert");
//    CodeMirrorVim.Vim.imap("`a", "\alpha", "insert");
//    CodeMirrorVim.IMAP('FMB', "\\mathbb{<++>}<++>", 'insert');
'

Thanks!!

p.s. In vim-latex, there are built-in keybindings for different modes. E.g., in insert mode, typing a specific three-letter combination automatically creates an equation environment with placeholders "<++>" in it in the .tex file. 

\begin{equation}
<++>
\label{<++>}
\end{end}

One can also create custom keybindings for vim-latex.

**Comment by nightwing** [comment]
Do these work with the old editor?
Also is `<++>` creating placeholder a default feature in vim or is it implemented by a plugin?

**Comment by dabingougou** [comment]
I have not tried these with the old editor. 

The <++> is not a vim feature, but an implementation by the vim-latex plugin. I am not sure if this is a possible thing in Codemirror, but I am curious if this can be done.

**Comment by llinfeng** [comment]
@dabingougou I'm in the same boat. Here is my current attempt - <https://gist.github.com/llinfeng/f50211be8ff2c8816934da266403f47d>. The first thing I'd like to solve is to jump to the corresponding line in PDF via `<localleader>lv`, or `;lv`. In the gist, the function is already defined. I just need a way to use `;lv` as a mapping in normal mode. This is filed in issue #88.

----

Looks like you'd like to replicate the following from vim-latex on Overleaf:
1. To insert snippets (templates) in insert mode, like \`a for `\alpha` for inline arguments, and, say `EIT`, `EQN` ... for multi-line snippets, and
2. A way to jump to the next `<++>` markers, say, with `<c-j>`, both in Normal mode and Insert mode.

I think these are doable by writing custom functions in JavaScript and making use of the rich set of [VIM Mode API](https://codemirror.net/5/doc/manual.html#vimapi). Let me know if you want to cost-share and outsource this to someone more proficient in JavaScript.

**Comment by nightwing** [comment]
https://github.com/replit/codemirror-vim/pull/105 fixes input mode mappings, so ``CodeMirrorVim.Vim.imap("`a", "\\alpha", "insert");`` should work after it is merged.
Since the `<++>` snippet, is not a vim feature, it can't be emulated with `map`, you'll need to define a command using snippet feature of codemirror, or do something else if `<++>` doesn't behave like textmate snippets.

**Comment by nightwing** [comment]
With recent fixes for keytokey mappings imap should work, and c-j for `<++>` can be implemented via search. Closing the issue, but please comment or open a new issue, if you still need further help.
