### ISSUE TITLE
Dead keys still don't work

### ISSUE THREAD

**Issue by kometenstaub** [replit/codemirror-vim#81]
#50 which was supposed to fix #13 doesn't work for me (on macOS, in both Chrome and Firefox).

I've tried it in the online test editor: https://codemirror-vim--util.repl.co/

When I get the chance, I'll try to reproduce on another OS to see whether it's macOS-specific.

**Comment by sergeichestakov** [comment]
weird @nightwing can you tal?

**Comment by nightwing** [comment]
The previous pull request have fixed it only for windows, the linked pull request should fix the issue on macOS too, please when you have time try it on https://raw.githack.com/replit/codemirror-vim/github-demo/dev/web-demo.html

**Comment by kometenstaub** [comment]
I've tested it on macOS in both Chrome and Firefox with both French and German locale, and it works for me. Thank you, @nightwing! :)

**Comment by lebigot** [comment]
Thanks for the fix.

I would add that keys like `^` and ` don't work in _Safari_ on macOS, through.
