### ISSUE TITLE
How to define leader key mappings in normal mode?

### ISSUE THREAD

**Issue by llinfeng** [replit/codemirror-vim#88]
I'm new to Codemirror and wonder if I can define `<localleader>lv` in normal mode. For now, `[s` can be mapped to trigger a custom function, as below:
``` js
    // Access the functions by defining them as actions first
    CodeMirrorVim.Vim.defineAction('forwardsearch', buctton_click_forward_search);
    CodeMirrorVim.Vim.defineAction('WritefullPrevious', writefull_previous_error);
    CodeMirrorVim.Vim.defineAction('WritefullNext', writefull_next_error);

    // Assign functions to key mappings.
    // CodeMirror.Vim.unmap(';');  // Cannot put this here - if uncommented, [s and ]s won't work
    CodeMirrorVim.Vim.mapCommand("[s", 'action', 'WritefullPrevious');
    CodeMirrorVim.Vim.mapCommand("]s", 'action', 'WritefullNext');
    CodeMirror.Vim.unmap(';');
    CodeMirrorVim.Vim.mapCommand(";lv", 'action', 'forwardsearch');  // This doesn't work.
```

Here is my current attempt in full - https://gist.github.com/llinfeng/f50211be8ff2c8816934da266403f47d. The goal is to revive [this old script](https://greasyfork.org/en/scripts/401089-overleaf-editor-custom-vim-keybindings-legacy-for-ace-editor-only) for Overleaf.

**Comment by nightwing** [comment]
What do you mean by "defining <localleader>lv"? vim plugin is the same for ace and codemirror, so you should be able to use your old code.

**Comment by llinfeng** [comment]
@nightwing I should be more precise - I was using `;` as my local leader, and would like to trigger a forward jump through `;lv`. With the example below, I only get `\lv` to work from the first line.
```
        CodeMirrorVim.Vim.mapCommand("\\lv", "action", "jumpToPdf");
        CodeMirror.Vim.unmap(';');
        CodeMirror.Vim.unmap('l');
        CodeMirrorVim.Vim.map(";lv", "\\lv", "normal")
```

And, thanks for pointing out that both ace and codemirror were accessing the same Vim Mode API. This is a big relief!

**Comment by nightwing** [comment]
I think you simply have a typo when calling `unmap`, `CodeMirror.Vim` instead of `CodeMirrorVim.Vim` which prevents the following lines from being executed.

**Comment by llinfeng** [comment]
Great catch! In summary, to use `;` as part of a mapping, one needs to first unmap it _properly_. The following two lines does the trick, taken from [this gist](https://gist.github.com/llinfeng/f50211be8ff2c8816934da266403f47d).
```
        // Use <localleader>lv, or ;lv - for forward search
        CodeMirrorVim.Vim.unmap(';');
        CodeMirrorVim.Vim.mapCommand(";lv", "action", "jumpToPdf");
```
