### ISSUE TITLE
Backtick (move to mark) doesn't work with French Mac keyboard

### ISSUE THREAD

**Issue by lebigot** [replit/codemirror-vim#91]
In normal mode, creating a mark (say with `ma`) and then moving to it with \`a does work: the backtick is ignored (and we switch to insert mode because of `a`).

This can be demonstrated on <https://raw.githack.com/replit/codemirror-vim/github-demo/dev/web-demo.html>.

**Comment by nightwing** [comment]
On which browser and which OS do you see this, for me ``ggmaG`a`` returns cursor to the start of document, as in vim itself.

**Comment by nightwing** [comment]
Sorry, i had missed the answer to my question in the title of the issue.

But i still couldn't reproduce it with `French` or `French -PC` layouts on mac.
