### ISSUE TITLE
Define custom keymaps in cm6

### ISSUE THREAD

**Issue by azmy60** [replit/codemirror-vim#99]
Is there a way that we can define custom keymaps using the cm6 api?

**Comment by nightwing** [comment]
If you mean keymaps that would invoke vim commands, then you need to use `Vim.map` as shown in the readme.

**Comment by azmy60** [comment]
Hey there! My bad, I tried using Vim.map, but it didn't work. I have to put the `vim()` all the way before all extensions to make it work. I think some of the extensions I'm using might be creating keymaps 🤷 .
